/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Wiwin Nur Hidayah
 */
public final class frmArrayTabelMahasiswa extends javax.swing.JFrame {
        private int selectedRow;
        private int index = 0;
    /**
     * Creates new form frmArrayTabelMahasiswa
     */
    public frmArrayTabelMahasiswa() {
        super("PEMROGRAMAN APLIKASI JAVA");
        initComponents();
        this.viewDataMahasiswa();
        this.pilih();
        
    }
     class MyList implements ListSelectionListener {

        public void valueChanged(ListSelectionEvent e) {

            if (e.getValueIsAdjusting()) {
                return;
            } 

            ListSelectionModel lsm = (ListSelectionModel) e.getSource();
            selectedRow = lsm.getMinSelectionIndex();
            TableModel tb = tblHasil.getModel();

            tfNim.setText(tb.getValueAt(selectedRow, 0).toString());
            tfNama.setText(tb.getValueAt(selectedRow, 1).toString());
            tfJalur.setText(tb.getValueAt(selectedRow, 2).toString());
            tfAsal.setText(tb.getValueAt(selectedRow, 3).toString());
            tfNomer.setText(tb.getValueAt(selectedRow, 4).toString());
            tfNim.setEditable(false);
        }
    }
 
    void pilih() {
        tblHasil.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
        ListSelectionModel rowSM = tblHasil.getSelectionModel();
        rowSM.addListSelectionListener(new MyList());

    }
 
    final void viewDataMahasiswa() {
        index = 0; 
        DefaultTableModel model;
        model = (DefaultTableModel) tblHasil.getModel();

        DBConnect connect = new DBConnect();
        Object[][] data = connect.getDataMahasiswa();
        if (model.getRowCount() == 0) {
            Object[] row;
            for (int i = 0; i < connect.getCountMahasiswa(); i++) {
                row = new Object[]{data[i][0], data[i][1], data[i][2], data[i][3], data[i][4]};
                model.addRow(row);
                index++;
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDaftar = new javax.swing.JLabel();
        lblNim = new javax.swing.JLabel();
        tfNim = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        lblJalur = new javax.swing.JLabel();
        tfJalur = new javax.swing.JTextField();
        lblAsal = new javax.swing.JLabel();
        tfAsal = new javax.swing.JTextField();
        lblNo = new javax.swing.JLabel();
        tfNomer = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDaftar.setText("DAFTAR MAHASISWA PTIK 2019");

        lblNim.setText("NIM");

        tfNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNimActionPerformed(evt);
            }
        });

        lblNama.setText("NAMA");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        lblJalur.setText("JALUR MASUK");

        tfJalur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJalurActionPerformed(evt);
            }
        });

        lblAsal.setText("ASAL DAERAH");

        tfAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAsalActionPerformed(evt);
            }
        });

        lblNo.setText("NO.HP");

        tfNomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomerActionPerformed(evt);
            }
        });

        btnTambah.setText("ADD");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("EDIT");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("DELETE");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "NAMA", "JALUR MASUK", "ASAL DAERAH", "NO.HP"
            }
        ));
        jScrollPane1.setViewportView(tblHasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDaftar)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNim)
                            .addComponent(lblNama)
                            .addComponent(lblJalur))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(61, 61, 61)
                                .addComponent(btnUbah)
                                .addGap(67, 67, 67)
                                .addComponent(btnHapus)
                                .addContainerGap(240, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNim, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(tfNama)
                                    .addComponent(tfJalur))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAsal)
                                    .addComponent(lblNo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfAsal, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(tfNomer))
                                .addGap(45, 45, 45))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblDaftar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNim)
                    .addComponent(lblAsal)
                    .addComponent(tfNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(lblNo)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJalur)
                    .addComponent(tfJalur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void tfNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNimActionPerformed

    private void tfJalurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJalurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJalurActionPerformed

    private void tfAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAsalActionPerformed

    private void tfNomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomerActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String nim = tfNim.getText();
        String nama = tfNama.getText();
        String jalurMasuk = tfJalur.getText();
        String asalDaerah = tfAsal.getText();
        String noHp = tfNomer.getText();
        tfNim.setText("");
        tfNama.setText("");
        tfJalur.setText("");
        tfAsal.setText("");
        tfNomer.setText("");
        DBConnect connect = new DBConnect();
        connect.setDataMahasiswa(nim, nama, jalurMasuk, asalDaerah, noHp);
        DefaultTableModel model;
        model = (DefaultTableModel) tblHasil.getModel();
        Object[] row;
        row = new Object[]{nim, nama, jalurMasuk, asalDaerah, noHp};
        model.addRow(row);   
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb;
        tb = (DefaultTableModel) tblHasil.getModel();

        String nim = tfNim.getText();
        String nama = tfNama.getText();
        String jalurMasuk = tfJalur.getText();
        String asalDaerah = tfAsal.getText();
        String noHp = tfNomer.getText();
        tb.setValueAt(nim, selectedRow, 0);
        tb.setValueAt(nama, selectedRow, 1);
        tb.setValueAt(jalurMasuk, selectedRow, 2);
        tb.setValueAt(asalDaerah, selectedRow, 3);
        tb.setValueAt(noHp, selectedRow, 4);
        DBConnect connect = new DBConnect();
        connect.updateMahasiswa(nama, jalurMasuk, asalDaerah, noHp, tb.getValueAt(selectedRow,0).toString());
        
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb;
        tb = (DefaultTableModel) tblHasil.getModel();
        String nm = (String) tb.getValueAt(selectedRow, 0); 
        
        for (int i = selectedRow; i < index-1; i++) {
            tb.setValueAt(tb.getValueAt(i + 1, 0), i, 0);
            tb.setValueAt(tb.getValueAt(i + 1, 1), i, 1);
            tb.setValueAt(tb.getValueAt(i + 1, 2), i, 2);
            tb.setValueAt(tb.getValueAt(i + 1, 3), i, 3);
            tb.setValueAt(tb.getValueAt(i + 1, 4), i, 4);
        }

        tb.setValueAt("", index-1, 0);
        tb.setValueAt("", index-1, 1);
        tb.setValueAt("", index-1, 2);
        tb.setValueAt("", index-1, 3);
        tb.setValueAt("", index-1, 4);
        index--;
        
        tfNim.setText("");
        tfNama.setText("");
        tfJalur.setText("");
        tfAsal.setText("");
        tfNomer.setText("");

        DBConnect connect = new DBConnect();
        connect.deleteMahasiswa(nm);
       
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmArrayTabelMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmArrayTabelMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmArrayTabelMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmArrayTabelMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmArrayTabelMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsal;
    private javax.swing.JLabel lblDaftar;
    private javax.swing.JLabel lblJalur;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private javax.swing.JLabel lblNo;
    private javax.swing.JTable tblHasil;
    private javax.swing.JTextField tfAsal;
    private javax.swing.JTextField tfJalur;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNim;
    private javax.swing.JTextField tfNomer;
    // End of variables declaration//GEN-END:variables

}
